stages:
  - test
  - build
  - deploy

variables:
  NESTED_VER: "1.0"
  DOCKER_TLS_CERTDIR: ""

build:compile:
  stage: build
  image: golang:latest
  script:
    - mkdir -p $CI_PROJECT_DIR/cmd/_build
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -mod=vendor -a -ldflags '-s' -o $CI_PROJECT_DIR/cmd/_build/cli-api ./cmd/cli-api
    - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -mod=vendor -a -ldflags '-s' -o $CI_PROJECT_DIR/cmd/_build/cli-admin ./cmd/cli-admin

  artifacts:
    untracked: true
    expire_in: 1 hour


deploy:production:
  stage: deploy
  only:
    - master
  image: docker:latest
  services:
    - docker:dind
  when: manual
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$NESTED_VER .
    - docker push $CI_REGISTRY_IMAGE:$NESTED_VER
  dependencies:
    - build:compile

deploy:staging:
  stage: deploy
  image: docker:latest
  except:
    - master
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:dev .
    - docker push $CI_REGISTRY_IMAGE:dev
  dependencies:
    - build:compile
