version: '2'
services:

  cyrus:
    restart: always
    image: registry.ronaksoft.com/nested/server:1.0
    container_name: nested-server
    ports:
      - "6061:6060"
      - "80:8080"
    environment:
      - NST_INSTANCE_ID=TEST_INSTANCE
      - NST_MONGO_DSN=mongodb://mongodb:27001/nested
      - NST_REDIS_DSN=cache:6379
      - NST_LOG_LEVEL=-1
      - NST_RUN_MODE=DEVELOPMENT
      - NST_DOMAINS=nested.local
      - NST_SENDER_DOMAIN=nested.local
      - NST_MAIL_STORE_SOCK=private/nested-mail
      - NST_FILE_SYSTEM_KEY=###SECUREKEY!!!
    networks:
      - test-nested


networks:
  test-nested:
    external:
      name: test-nested
