version: '2'

services:
  # MONGO DB
  mongodb:
    restart: always
    image: mongo
    container_name: nested-mongo
    command: mongod --config /ronak/config.yml
    ports:
      - "27001:27001"
    volumes:
      - ./_hdd/mongo:/data/db:rw
      - ./mongo-config.yml:/ronak/config.yml
    networks:
      - test-nested

networks:
  test-nested:
    external:
      name: test-nested
