version: '2'
services:

  cyrus:
    restart: always
    image: registry.ronaksoft.com/nested/server:1.0
    container_name: nested-server
    ports:
      - "6061:6060"
      - "8080:8080"
    environment:
      - NST_INSTANCE_ID=TEST_INSTANCE
      - NST_MONGO_DSN=mongodb://mongodb:27001/nested
      - NST_REDIS_DSN=cache:6379
      - NST_LOG_LEVEL=-1
      - NST_RUN_MODE=DEVELOPMENT
      - NST_DOMAINS=nested.local
      - NST_SENDER_DOMAIN=nested.local
      - NST_MAIL_STORE_SOCK=private/nested-mail
      - NST_SYSTEM_API_KEY=###SECUREKEY!!!
      - NST_SMTP_USER=smtpUser
      - NST_SMTP_PASS=smtpPass
    volumes:
      - ./postfix/certs/:/etc/postfix/certs:rw
      - ./postfix/domainkeys/:/etc/opendkim/domainkeys:rw
    networks:
      - test-nested

  webapp:
    restart: always
    image: registry.ronaksoft.com/nested/legacy/web-app:v4.10.25
    container_name: nested-webapp
    ports:
      - "80:80"
    networks:
      - test-nested
    environment:
      - NST_HTTP_CYRUS_URL=http://localhost
      - NST_WS_CYRUS_URL=ws://localhost
      - NST_UPLOAD_SIZE_LIMIT=104857600
      - NST_DOMAIN=nested.local
      - SHOW_FOOTER=true
      - DEFAULT_LOCALE=fa

networks:
  test-nested:
    external:
      name: test-nested
