version: '2'
services:

  cyrus:
    restart: always
    image: registry.ronaksoft.com/nested/legacy/server:1.0
    container_name: nested-server
    ports:
      - "80:8080"
      - "25:25"
      - "587:587"
    environment:
      - NST_INSTANCE_ID=TEST_INSTANCE
      - NST_MONGO_DSN=mongodb://mongodb:27001/nested
      - NST_REDIS_DSN=cache:6379
      - NST_LOG_LEVEL=-1
      - NST_RUN_MODE=DEVELOPMENT
      - NST_DOMAINS=ronaksoftware.com
      - NST_SENDER_DOMAIN=ronaksoftware.com
      - NST_MAIL_STORE_SOCK=private/nested-mail
      - NST_MAIL_UPLOAD_BASE_URL=http://127.0.0.1:8080
      - NST_SYSTEM_API_KEY=SOME_SECURE_KEY
      - NST_SMTP_USER=smtpUser
      - NST_SMTP_PASS=smtpPass
    volumes:
      - ./postfix/certs/:/etc/postfix/certs:rw
      - ./postfix/domainkeys/:/etc/opendkim/domainkeys:rw
    networks:
      - test-nested

networks:
  test-nested:
    external:
      name: test-nested
