version: '2'

services:

  # KeyDB Permanent/Counter/Temp Cache
  cache:
    restart: always
    image: redis
    container_name: nested-redis
    privileged: true
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - test-nested
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./_hdd/cache/:/data:rw
#    ports:
#      - "6379:6379"



  # MONGO DB
  mongodb:
    restart: always
    image: mongo
    container_name: nested-mongo
    command: mongod --config /ronak/config.yml
    ports:
      - "27001:27001"
    volumes:
      - ./_hdd/mongo:/data/db:rw
      - ./mongo-config.yml:/ronak/config.yml
    networks:
      - test-nested

networks:
  test-nested:
    external:
      name: test-nested
