version: '2'
services:
  ijob:
    image: registry.ronaksoftware.com/base/nats:latest
    command: nats --user=ronak --pass=P0uyan

  xjob:
    image: registry.ronaksoftware.com/base/nats:latest
    command: nats --user=ronak --pass=P0uyan

  worker:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/go/src/git.ronaksoftware.com/nested/server-router
    links:
      - ijob:intern.job.nst
      - xjob:extern.job.nst
