version: '2'
services:
# JOB service
  job:
    image: registry.ronaksoft.com/base/nats
    networks:
      default:
        aliases:
          - job.cyrus.nst

# NTFY service
  ntfy:
    restart: always
    image: registry.ronaksoft.com/nested/server-ntfy:3
    networks:
      - default
      - db-mongo-net
      - cache-redis-net
    environment:
      - NST_BUNDLE_ID={{.Cyrus.BundleID}}
      - NST_MONGO_DSN={{.MongoDataDSN}}
      - NST_REDIS_DSN={{.RedisCacheDSN}}
      - NST_GCM_API_KEY={{.GoogleAPIKey}}
      - NST_DEBUG_LEVEL={{.Cyrus.DebugLevel}}
      - NST_RUN_MODE=DEVELOPMENT
      - NST_JOB_ADDRESS=nats://job.cyrus.nst:4222
      - NST_JOB_WORKERS_COUNT=10
      - NST_JOB_WORKERS_BUFFER_SIZE=1000
      - NST_APN_CERT_FILE=/ronak/certs/nested.p12

# GATEWAY service
  gateway:
    restart: always
    image: registry.ronaksoft.com/nested/server-gateway:3.0
    depends_on:
      - ntfy
    volumes:
      - ./certs/:/ronak/certs
    networks:
      - default
      - db-mongo-net
      - cache-redis-net
    ports:
      - {{.Cyrus.Port}}:{{.Cyrus.Port}}
    environment:
      - NST_DOMAIN={{.Domain}}
      - NST_BUNDLE_ID={{.Cyrus.BundleID}}
      - NST_BIND_ADDRESS=0.0.0.0:{{.Cyrus.Port}}
      - NST_MONGO_DSN={{.MongoDataDSN}}
      - NST_REDIS_DSN={{.RedisCacheDSN}}
      - NST_DEBUG_LEVEL={{.Cyrus.DebugLevel}}
      - NST_JOB_ADDRESS=nats://job.cyrus.nst:4222
      - NST_JOB_SUBJECT=USERAPI
      - NST_JOB_WORKERS_COUNT=30
      - NST_JOB_WORKERS_BUFFER_SIZE=100
      - NST_TLS_KEY_FILE={{if .Cyrus.Secure}}/ronak/certs/cyrus.key{{end}}
      - NST_TLS_CERT_FILE={{if .Cyrus.Secure}}/ronak/certs/cyrus.crt{{end}}
      - NST_WEBAPP_BASE_URL={{.Cyrus.WebappBaseUrl}}
      - NST_FILE_SYSTEM_KEY={{.CyrusFileSystemKey}}
      - NST_SMTP_HOST=mta
      - NST_SMTP_PORT=25
      - NST_SMTP_USER={{.Cyrus.SMTPUser}}
      - NST_SMTP_PASS={{.Cyrus.SMTPPass}}
      - NST_CYRUS_URL={{.Cyrus.CyrusUrl}}

# MTA Service
 mta:
    restart: always
    image: registry.ronaksoft.com/nested/server-mta:1.0
    ports:
      - "25:25"
      - "587:587"
    networks:
      - default
      - db-mongo-net
      - cache-redis-net
    volumes:
      - ./certs:/etc/postfix/certs
      - ./domainkeys:/etc/opendkim/domainkeys
    environment:
      - NST_DOMAIN={{.Domain}}
      - NST_MONGO_DSN={{.MongoDataDSN}}
      - NST_REDIS_DSN={{.RedisCacheDSN}}
      - NST_CYRUS_URL={{.Gobryas.CyrusUrl}}
      - NST_CYRUS_FILE_SYSTEM_KEY={{.CyrusFileSystemKey}}
      - NST_CYRUS_INSECURE_HTTPS={{if .Gobryas.CertificateCheck}}false{{else}}true{{end}}
      - NST_SMTP_CRED={{.Gobryas.SMTPUser}}:{{.Gobryas.SMTPPass}}

# ROUTER service
 router:
    restart: always
    image: registry.ronaksoft.com/nested/server-router:1.0
    command: -v 3
    depends_on:
      - gateway
    networks:
      - default
      - arsaces-net
    environment:
      - NST_BUNDLE_ID={{.Cyrus.BundleID}}
      - NST_JOB_EXT_ADDRESS={{.ExternalJobUrl}}
      - NST_JOB_EXT_WORKERS_COUNT=50
      - NST_JOB_EXT_WORKERS_BUFFER_SIZE=100
      - NST_JOB_INT_ADDRESS=nats://job.cyrus.nst:4222
      - NST_JOB_INT_WORKERS_COUNT=50
      - NST_JOB_INT_WORKERS_BUFFER_SIZE=100

networks:
  default:
    external: true
    name: cyrus-net
  arsaces-net:
    external: true
    name: arsaces-net
  db-mongo-net:
    external: true
    name: db-mongo-net
  cache-redis-net:
    external: true
    name: cache-redis-net
