version: '2'
services:
  db-mongo:
    restart: always
    image: registry.ronaksoftware.com/base/mongo:latest
    command: mongod --config /ronak/config.yml
    volumes:
      - ./certs:/ronak/certs/
      - ./.vol:/data/db:rw
      - ./config.yml:/ronak/config.yml
    networks:
      default:
        aliases:
          - db-mongo.nst
    {{if .Mongo.PortExposed}}
    ports:
      - {{.Mongo.Port}}:{{.Mongo.Port}}
    {{end}}

networks:
  default:
    external:
      name: db-mongo-net
