version: '2'
services:
# JOB service
  job:
    image: registry.ronaksoft.com/base/nats
    networks:
      default:
        aliases:
          - job.cyrus.nst

# GATEWAY service
  gateway:
    restart: always
    image: registry.ronaksoft.com/nested/server-gateway:1.0
    volumes:
      - ./certs/:/ronak/certs
    networks:
      - default
      - db-mongo-net
    ports:
      - 81:81
      - 2374:2374
    environment:
      - NST_DOMAIN=ronaksoftware.com
      - NST_BUNDLE_ID=CYRUS-001
      - NST_BIND_ADDRESS=0.0.0.0:81
      - NST_MONGO_DSN=mongodb://db-mongo.nst:27001
      - NST_REDIS_DSN=cache-redis.nst:6379
      - NST_DEBUG_LEVEL=0
      - NST_JOB_ADDRESS=nats://job.cyrus.nst:4222
      - NST_JOB_SUBJECT=USERAPI
      - NST_JOB_WORKERS_COUNT=10
      - NST_JOB_WORKERS_BUFFER_SIZE=1000
      - NST_TLS_KEY_FILE=/ronak/certs/cyrus.key
      - NST_TLS_CERT_FILE=/ronak/certs/cyrus.crt

networks:
  default:
    external:
      name: cyrus-net
  db-mongo-net:
    external:
      name: db-mongo-net